/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.inventory;

import com.inventory.controller.InventoryController;
import com.inventory.models.dbentities.Category;
import com.inventory.models.dbentities.Inventory;
import com.inventory.models.dbentities.Product;
import com.inventory.models.dbentities.Productbrand;
import com.inventory.repository.InventoryPersistence;
import minionProject_inventory.App;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class AppTest {

    private InventoryPersistence inventoryPersistence;
    private InventoryController inventoryController;

    public AppTest(){
        inventoryPersistence = new InventoryPersistence();
        inventoryController = new InventoryController();
    }

    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testNotNullListShowProduct() {
        List actual = inventoryPersistence.showProducts();
        assertNotNull(actual);
    }

    @Test
    public void testNullListRetrieveProduct() {
        int productId = 20;
        Product actualResult = inventoryPersistence.retrieveProduct(productId);
        assertNull(actualResult);
    }

    /*@Test
    public void testListRetrieveProduct() {
        int productId = 1;
        List actualResult = inventoryPersistence.retrieveProduct(productId);
        assertTrue();
    }*/

    @Test
    public void testNotNullShowCategories() {
        List actualResult = inventoryPersistence.showCategories();
        assertNotNull(actualResult);
    }

    @Test
    public void testNullListRetrieveCategories() {
        int categoryId = 20;
        Category actualResult = inventoryPersistence.retrieveCategory(categoryId);
        //assertNull(actualResult);
        assertNotNull(actualResult);
    }

    @Test
    public void testNotNullShowInventory() {
        List actualResult = inventoryPersistence.showInventories();
        assertNotNull(actualResult);
    }

    @Test
    public void testShowProductsBrands() {
        List actualProductBrands = inventoryController.showProductBrands();
        assertNotNull(actualProductBrands);
    }

}
